### ISSUE TITLE
use Linux ! 

### ISSUE THREAD

**Issue by equivalent** [simi/mac-test#1]
![Logo-history-revision](https://user-images.githubusercontent.com/721990/137640748-80abc81b-6231-477d-8a91-5b67cb6d115c.jpg)
Picus panelakovy !  :D

**Comment by simi** [comment]
Snad jsi si nemyslel, že jsem opustil mojí Fedořičku milovanou.

**Comment by equivalent** [comment]
Neuveris, zrovna preinstalujem moje Ubuntu nenavidene po 4585krat  :heart:
